server:
  port: 8980
  context-path: /TestSpringBoot
  jsp-servlet:
    init-parameters:
      ddevelopment: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: classpath:/com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity